### ISSUE TITLE
Variables need to be cleared for next generation

### ISSUE THREAD

**Issue by JenniferByrnes** [JenniferByrnes/password-gen#3]
### When user generates a 2nd password, it is added to the 1st.
clear out the password before running the generation function a second time.
re-initialize all variables for a 2nd pass.

**Comment by LucasChlz** [comment]
Hello, I sent a pull request to implement this, could you check?

**Comment by JenniferByrnes** [comment]
Lucas,

I’m a student taking a class and this is one of our projects.  Thanks for the help, but I’m doing this on my own and simulating a work environment is part of the class.

Good luck to you!
